---
startDelaySeconds: 0
hostPort: 127.0.0.1:9999
username:
password:
ssl: false
lowercaseOutputName: false
lowercaseOutputLabelNames: false

## exclude some jvm metrics you don't need
blacklistObjectNames: ["jvm.memory.bytes.used:type=area,*",
                       "jvm.memory.bytes.used:type=pool,*",
                       "jvm.memory.bytes.max:type=area,*"]

rules:
  - pattern: 'me.rotemfo.counters.timer<type=ROOT, name=(.*)><>Count'
    name: rotem_root_counter_$1
  - pattern: 'me.rotemfo.counters.timer<type=HTTP, name=(.*)><>Count'
    name: rotem_counter_$1
  - pattern: 'me.rotemfo.counters.timer<type=HTTP, name=(.*)><>Max'
    name: rotem_counter_max_$1
  - pattern: 'me.rotemfo.counters.timer<type=HTTP, name=(.*)><>Min'
    name: rotem_counter_min_$1
  - pattern: 'me.rotemfo.counters.meter<type=HTTP, name=(.*)><>Count'
    name: rotem_meter_$1
  - pattern: 'me.rotemfo.counters.meter<type=HTTP, name=(.*)><>MeanRate'
    name: rotem_meter_meanrate_$1
  - pattern: 'me.rotemfo.counters.meter<type=HTTP, name=(.*)><>OneMinuteRate'
    name: rotem_meter_1minrate_$1
  - pattern: 'me.rotemfo.counters.meter<type=HTTP, name=(.*)><>FiveMinuteRate'
    name: rotem_meter_5minrate_$1
